### ISSUE TITLE
部门列表预设，部门信息新增要求

### ISSUE THREAD

**Issue by ZTao-z** [OtakuTools/WordPrinter#16]

**Comment by Ming-zz** [comment]
请详细

**Comment by ZTao-z** [comment]
按照需求文档中的部门初始化信息进行填写

**Comment by Ming-zz** [comment]
![image](https://user-images.githubusercontent.com/35625369/55893424-cbbac280-5bea-11e9-9270-35c528c5ad7c.png)

**Comment by Ming-zz** [comment]
![image](https://user-images.githubusercontent.com/35625369/56483598-86a56300-64fd-11e9-828c-8feb558e0771.png)
