### ISSUE TITLE
zero project

### ISSUE THREAD

**Issue by Ming-zz** [OtakuTools/WordPrinter#45]
当`user.projects`为`[]`时(`None`情况未测试)，`生成文档`的`四层项目`下可选`XXX项目`，且显示`生成文档成功`,但不会有文档被成功生成当`user.projects`为`[]`时(`None`情况未测试)，`生成文档`的`四层项目`下可选`XXX项目`，且显示`生成文档成功`,但不会有文档被成功生成

**Comment by ZTao-z** [comment]
这个问题，暂时先放着吧

**Comment by Ming-zz** [comment]
wontfix
