### ISSUE TITLE
bug：四层项目文件替换

### ISSUE THREAD

**Issue by ZTao-z** [OtakuTools/WordPrinter#50]
四层项目文件\09变更管理程序下\ZRXX-20000-CH-R-02 变更管理统计报表-XXX项目“变更数量没有取值"

**Comment by ZTao-z** [comment]
![0c57feac0da6ffa405d8496d32d28ad](https://user-images.githubusercontent.com/23055040/63483366-b9bd2a80-c4ce-11e9-9489-232461fb173c.jpg)

**Comment by Ming-zz** [comment]
变更数量已可变，但图表无法做
